FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./

RUN npm config set registry https://registry.npmjs.org/ \
&& npm config set fetch-retries 5 \
&& npm config set fetch-retry-mintimeout 10000 \
&& npm config set fetch-retry-maxtimeout 60000

RUN npm ci --omit=dev

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
