apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  labels:
    app: app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: backend
          image: 863518419988.dkr.ecr.eu-west-1.amazonaws.com/app-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://app-mysql:3306/orar"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "3676"
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
  labels:
    app: app-backend
spec:
  type: ClusterIP
  selector:
    app: app-backend
  ports:
    - port: 8080
      targetPort: 8080
