# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels:
    app: app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
        - name: frontend
          image: 863518419988.dkr.ecr.eu-west-1.amazonaws.com/app-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
  labels:
    app: app-frontend
spec:
  type: NodePort
  selector:
    app: app-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
